"""initial_schema

Revision ID: c597a93fa003
Revises: 
Create Date: 2026-09-13 01:37:54.507740
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

revision: str = 'c597a93fa003'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('payload_version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','running','succeeded','failed','cancelled')", name='ck_jobs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_dedupe_key'), 'analysis_jobs', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_job_type'), 'analysis_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_index('ix_jobs_claim', 'analysis_jobs', ['status', 'run_after', 'priority', 'created_at'], unique=False)
    op.create_index('uq_jobs_active_dedupe', 'analysis_jobs', ['dedupe_key'], unique=True, postgresql_where=sa.text("status IN ('pending','running')"), sqlite_where=sa.text("status IN ('pending','running')"))
    op.create_table('opening_explorer_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('request_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index(op.f('ix_opening_explorer_cache_expires_at'), 'opening_explorer_cache', ['expires_at'], unique=False)
    op.create_table('player_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chess_com_username', sa.String(length=64), nullable=False),
    sa.Column('chess_com_username_normalized', sa.String(length=64), nullable=False),
    sa.Column('target_rating', sa.Integer(), nullable=False),
    sa.Column('default_time_class', sa.String(length=24), nullable=False),
    sa.Column('weekly_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_profiles_chess_com_username_normalized'), 'player_profiles', ['chess_com_username_normalized'], unique=True)
    op.create_table('position_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('fen', sa.Text(), nullable=False),
    sa.Column('engine_name', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('nodes', sa.Integer(), nullable=False),
    sa.Column('multipv', sa.Integer(), nullable=False),
    sa.Column('uci_options', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('wdl_white_win', sa.Integer(), nullable=False),
    sa.Column('wdl_draw', sa.Integer(), nullable=False),
    sa.Column('wdl_white_loss', sa.Integer(), nullable=False),
    sa.Column('expected_score_white', sa.Float(), nullable=False),
    sa.Column('score_cp', sa.Integer(), nullable=True),
    sa.Column('mate_in', sa.Integer(), nullable=True),
    sa.Column('best_move_uci', sa.String(length=8), nullable=True),
    sa.Column('lines', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_analyses_cache_key'), 'position_analyses', ['cache_key'], unique=True)
    op.create_table('archive_fetch_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('archive_url', sa.Text(), nullable=False),
    sa.Column('archive_month', sa.String(length=7), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=255), nullable=True),
    sa.Column('fetch_status', sa.String(length=24), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'archive_url', name='uq_archive_profile_url')
    )
    op.create_index(op.f('ix_archive_fetch_states_profile_id'), 'archive_fetch_states', ['profile_id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('source_game_id', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('pgn_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_pgn', sa.Text(), nullable=False),
    sa.Column('parse_status', sa.String(length=24), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('rules', sa.String(length=32), nullable=False),
    sa.Column('rated', sa.Boolean(), nullable=False),
    sa.Column('time_class', sa.String(length=24), nullable=False),
    sa.Column('time_control', sa.String(length=32), nullable=False),
    sa.Column('white_name', sa.String(length=64), nullable=False),
    sa.Column('black_name', sa.String(length=64), nullable=False),
    sa.Column('white_rating', sa.Integer(), nullable=True),
    sa.Column('black_rating', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=12), nullable=False),
    sa.Column('termination', sa.Text(), nullable=True),
    sa.Column('opening_name', sa.String(length=255), nullable=True),
    sa.Column('eco', sa.String(length=8), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('player_color', sa.String(length=8), nullable=False),
    sa.Column('player_rating', sa.Integer(), nullable=True),
    sa.Column('opponent_rating', sa.Integer(), nullable=True),
    sa.Column('headers', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('analysis_status', sa.String(length=24), nullable=False),
    sa.Column('review_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("analysis_status IN ('not_queued','queued','running','complete','failed')", name='ck_games_analysis_status'),
    sa.CheckConstraint("player_color IN ('white','black')", name='ck_games_player_color'),
    sa.ForeignKeyConstraint(['profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'pgn_hash', name='uq_game_profile_pgn_hash')
    )
    op.create_index(op.f('ix_games_played_at'), 'games', ['played_at'], unique=False)
    op.create_index(op.f('ix_games_profile_id'), 'games', ['profile_id'], unique=False)
    op.create_index('ix_games_profile_played', 'games', ['profile_id', 'played_at', 'id'], unique=False)
    op.create_index(op.f('ix_games_source_game_id'), 'games', ['source_game_id'], unique=False)
    op.create_index('uq_games_source_id', 'games', ['source', 'source_game_id'], unique=True, postgresql_where=sa.text('source_game_id IS NOT NULL'), sqlite_where=sa.text('source_game_id IS NOT NULL'))
    op.create_table('metric_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('time_class', sa.String(length=24), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('game_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('analysis_version', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_snapshots_profile_id'), 'metric_snapshots', ['profile_id'], unique=False)
    op.create_table('weekly_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('focus_topics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('activities', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('algorithm_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'week_start', 'algorithm_version', name='uq_weekly_plan')
    )
    op.create_index(op.f('ix_weekly_plans_profile_id'), 'weekly_plans', ['profile_id'], unique=False)
    op.create_table('moves',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('side_to_move', sa.String(length=8), nullable=False),
    sa.Column('san', sa.String(length=24), nullable=False),
    sa.Column('uci', sa.String(length=8), nullable=False),
    sa.Column('fen_before', sa.Text(), nullable=False),
    sa.Column('fen_after', sa.Text(), nullable=False),
    sa.Column('clock_ms', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=24), nullable=False),
    sa.Column('is_book', sa.Boolean(), nullable=False),
    sa.CheckConstraint("phase IN ('opening','middlegame','endgame')", name='ck_moves_phase'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'ply', name='uq_move_game_ply')
    )
    op.create_index(op.f('ix_moves_game_id'), 'moves', ['game_id'], unique=False)
    op.create_table('move_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('move_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_version', sa.String(length=64), nullable=False),
    sa.Column('before_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('after_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('expected_loss', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('forced_mate_changed', sa.Boolean(), nullable=False),
    sa.Column('search_unstable', sa.Boolean(), nullable=False),
    sa.CheckConstraint("severity IN ('normal','inaccuracy','mistake','blunder')", name='ck_assessment_severity'),
    sa.ForeignKeyConstraint(['after_analysis_id'], ['position_analyses.id'], ),
    sa.ForeignKeyConstraint(['before_analysis_id'], ['position_analyses.id'], ),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('move_id', 'analysis_version', name='uq_move_assessment_version')
    )
    op.create_index(op.f('ix_move_assessments_move_id'), 'move_assessments', ['move_id'], unique=False)
    op.create_table('mistakes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('move_assessment_id', sa.String(length=36), nullable=False),
    sa.Column('theme', sa.String(length=64), nullable=False),
    sa.Column('facts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('explanation_zh', sa.Text(), nullable=False),
    sa.Column('recommended_move_uci', sa.String(length=8), nullable=True),
    sa.Column('recommended_move_san', sa.String(length=24), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['move_assessment_id'], ['move_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('move_assessment_id', 'theme', name='uq_mistake_theme')
    )
    op.create_index(op.f('ix_mistakes_move_assessment_id'), 'mistakes', ['move_assessment_id'], unique=False)
    op.create_table('training_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('mistake_id', sa.String(length=36), nullable=False),
    sa.Column('fen', sa.Text(), nullable=False),
    sa.Column('side_to_move', sa.String(length=8), nullable=False),
    sa.Column('answer_moves', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('solution_pv', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('theme', sa.String(length=64), nullable=False),
    sa.Column('interval_level', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mistake_id'], ['mistakes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mistake_id')
    )
    op.create_index(op.f('ix_training_items_due_at'), 'training_items', ['due_at'], unique=False)
    op.create_index(op.f('ix_training_items_profile_id'), 'training_items', ['profile_id'], unique=False)
    op.create_table('training_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=64), nullable=False),
    sa.Column('training_item_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_move_uci', sa.String(length=8), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('used_hint', sa.Boolean(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('previous_level', sa.Integer(), nullable=False),
    sa.Column('new_level', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['training_item_id'], ['training_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_attempts_attempt_id'), 'training_attempts', ['attempt_id'], unique=True)
    op.create_index(op.f('ix_training_attempts_training_item_id'), 'training_attempts', ['training_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_attempts_training_item_id'), table_name='training_attempts')
    op.drop_index(op.f('ix_training_attempts_attempt_id'), table_name='training_attempts')
    op.drop_table('training_attempts')
    op.drop_index(op.f('ix_training_items_profile_id'), table_name='training_items')
    op.drop_index(op.f('ix_training_items_due_at'), table_name='training_items')
    op.drop_table('training_items')
    op.drop_index(op.f('ix_mistakes_move_assessment_id'), table_name='mistakes')
    op.drop_table('mistakes')
    op.drop_index(op.f('ix_move_assessments_move_id'), table_name='move_assessments')
    op.drop_table('move_assessments')
    op.drop_index(op.f('ix_moves_game_id'), table_name='moves')
    op.drop_table('moves')
    op.drop_index(op.f('ix_weekly_plans_profile_id'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_index(op.f('ix_metric_snapshots_profile_id'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index('uq_games_source_id', table_name='games', postgresql_where=sa.text('source_game_id IS NOT NULL'))
    op.drop_index(op.f('ix_games_source_game_id'), table_name='games')
    op.drop_index('ix_games_profile_played', table_name='games')
    op.drop_index(op.f('ix_games_profile_id'), table_name='games')
    op.drop_index(op.f('ix_games_played_at'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_archive_fetch_states_profile_id'), table_name='archive_fetch_states')
    op.drop_table('archive_fetch_states')
    op.drop_index(op.f('ix_position_analyses_cache_key'), table_name='position_analyses')
    op.drop_table('position_analyses')
    op.drop_index(op.f('ix_player_profiles_chess_com_username_normalized'), table_name='player_profiles')
    op.drop_table('player_profiles')
    op.drop_index(op.f('ix_opening_explorer_cache_expires_at'), table_name='opening_explorer_cache')
    op.drop_table('opening_explorer_cache')
    op.drop_index('uq_jobs_active_dedupe', table_name='analysis_jobs', postgresql_where=sa.text("status IN ('pending','running')"))
    op.drop_index('ix_jobs_claim', table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_job_type'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_dedupe_key'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
